#!/bin/zsh


eza input/ | xargs -I % sh -c 'base=$(basename % .fastq.gz); ${PWD}/workflows/assemble_reads_generate_MAGS.nf --sampleid ${base} --inputdir ${PWD}/input'

${PWD}/workflows/create_MAG_catalogue.nf --outdir ${PWD}/results -resume

eza input/ | xargs -I % sh -c 'base=$(basename % .fastq.gz); ${PWD}/workflows/mapping_mags.nf --sampleid ${base} --outdir ${PWD}/results'

${PWD}/workflows/binning_classification.nf --outdir ${PWD}/results -resume

