#!/bin/zsh

eza input/ | xargs -I % sh -c 'base=$(basename % .fastq.gz); workflows/assemble_reads_generate_MAGS.nf --sampleid ${base} --inputdir input'

workflows/create_MAG_catalogue.nf

eza input/ | xargs -I % sh -c 'base=$(basename % .fastq.gz); workflows/mapping_mags.nf --sampleid ${base}'

workflows/binning_classification.nf
