#!/bin/zsh

eza input/ | xargs -I % sh -c 'base=$(basename % .fastq.gz); nextflow run workflows/assemble_reads_generate_MAGS.nf --sampleid ${base} --inputdir input'

nextflow run workflows/create_MAG_catalogue.nf

eza input/ | xargs -I % sh -c 'base=$(basename % .fastq.gz); nextflow run workflows/mapping_mags.nf --sampleid ${base}'

nextflow run workflows/binning_classification.nf
